routes/admin.php
<?php

Route::get('/', function() {
    return 'dahsboard';
})->name('dashboard');

Route::resource('categories', 'CategoryController');
Route::resource('products', 'ProductController');


Route::get('data/categories', 'DataTable\CategoryController')->name('categories.data');
Route::get('data/products', 'DataTable\ProductController')->name('products.data');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::livewire('/', 'home')->name('index');
Route::livewire('/product/{product:slug}', 'product-detail')->name('product.detail');
Route::livewire('/cart', 'cart-index')->name('cart.index');
Route::livewire('/checkout', 'checkout')->name('checkout.index');
Route::livewire('/payment/{order}', 'payment')->name('payment.index');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    public $timestamps = false;

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:3'
        ]);

        Category::create($request->only('name'));

        session()->flash('message', 'Data sucessfully added');

        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit', [
            'category' => $category,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->only('name'));

        session()->flash('message', 'Data updated sucessfully');

        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return response()->json(['success' => true]);
    }
}

app/Http/Controllers/Admin/DataTable/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\DataTable;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke()
    {
        $categories = Category::orderBy('name', 'asc');

        return datatables()->of($categories)
                    ->addColumn('action','admin.templates.partials.DT-action')
                    ->addIndexColumn()
                    ->toJson();
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.templates.default')

@section('title', 'Create a Category')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">

        <div class="card-header">
          <h3 class="card-title">Create Category</h3>
        </div>

        <form action="{{ route('admin.categories.store') }}" method="POST">
          @csrf

          <div class="card-body">
            <div class="form-group">
              <label for="">Category Name</label>
              <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter a category name" value="{{ old('name') }}">

               @error('name')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>
          </div>

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Tambahkan</button>
          </div>
        </form>

      </div>
    </div>
  </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.templates.default')

@section('title', 'Update Category')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">

        <div class="card-header">
          <h3 class="card-title">Edit Category</h3>
        </div>

        <form action="{{ route('admin.categories.update', $category) }}" method="POST">
          @csrf
          @method('put')
          <div class="card-body">
            <div class="form-group">
              <label for="">Category Name</label>
              <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter a category name" value="{{ old('name') ?? $category->name }}">

               @error('name')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>
          </div>

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </form>

      </div>
    </div>
  </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.templates.default')

@section('title', 'Data Categories')

@section('content')
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Data Categories</h3>
    </div>
    <div class="card-body">
      @if(session()->has('message'))
        <div class="alert alert-info">{{ session('message')  }}</div>
      @endif
      <a href="{{ route('admin.categories.create')  }}" class="btn btn-primary mb-4">Add Category</a>
      <table id="dataTable" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Slug</th>
            <th>Aksi</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">
@endpush

@push('scripts')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script>
  $(function() {
    $('#dataTable').DataTable({
      "processing": true,
      "serverSide": true,
      "responsive": true,
      "autoWidth": true,
      ajax: '{{ route('admin.categories.data') }}',
      columns: [
        {data: 'DT_RowIndex', orderable: false, searachable: false},
        {data: 'name'},
        {data: 'slug'},
        {data: 'action'},
      ]
    })
  })

  $('#dataTable').on('click', 'button#delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');

    Swal.fire({
      title: 'Kamu yakin hapus data ini?',
      text: "Data yang dihapus tidak bisa dikembalikan!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Oke, Hapus!',
      cancelButtonText: 'Batalkan',
    }).then((result) => {
      if (result.value) {
        $.ajax({
          type: 'DELETE',
          url: '/admin/categories/' + id,
          data: {
            'id': id,
             '_token': "{{ csrf_token() }}"
          },
          success: function(response) {
            Swal.fire(
              'Dihapus!',
              'Data berhasil dihapus.',
              'success'
            )

            location.reload(true);
          },
        });
      }
    })
  })

</script>
@endpush