routes/admin.php
<?php

Route::get('/', function() {
    return 'dahsboard';
})->name('dashboard');

Route::resource('categories', 'CategoryController');
Route::resource('products', 'ProductController');


Route::get('data/categories', 'DataTable\CategoryController')->name('categories.data');
Route::get('data/products', 'DataTable\ProductController')->name('products.data');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::livewire('/', 'home')->name('index');
Route::livewire('/product/{product:slug}', 'product-detail')->name('product.detail');
Route::livewire('/cart', 'cart-index')->name('cart.index');
Route::livewire('/checkout', 'checkout')->name('checkout.index');
Route::livewire('/payment/{order}', 'payment')->name('payment.index');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function getImage()
    {
        return asset('storage/' . $this->image);
    }
}

app/Http/Controllers/Admin/DataTable/ProductController.php
<?php

namespace App\Http\Controllers\Admin\DataTable;

use App\Http\Controllers\Controller;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $products = Product::latest();

        return datatables()->of($products)
                    ->addColumn('action','admin.templates.partials.DT-action')
                    ->addColumn('image', function(Product $model) {
                        return '<img src="'. $model->getImage() .'" height="150px"/>';
                    })
                    ->addIndexColumn()
                    ->rawColumns(['image', 'action'])
                    ->toJson();
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductFormRequest;
use App\Product;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.create', [
            'categories' => Category::orderBy('name', 'asc')->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductFormRequest $request)
    {
        $image = null;

        if ($request->hasFile('image')) {
            $image = $request->file('image')->store('products');
        }

        $categories = Category::find($request->categories);

        $data = array_merge(
                    $request->except('_token', 'categories', 'image'),
                    compact('image')
                );

        $product = Product::create($data);

        $product->categories()->attach($categories);

        session()->flash('message', 'Product added successfully.');

        return redirect()->route('admin.products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.product.edit', [
            'categories' => Category::orderBy('name', 'asc')->get(),
            'product' => $product,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductFormRequest $request, Product $product)
    {
        $image = $product->image ?? null;

        if ($request->hasFile('image')) {
            if ($product->image) {
                Storage::delete($product->image);
            }

            $image = $request->file('image')->store('products');
        }

        $categories = Category::find($request->categories);

        $data = array_merge(
                    $request->except('_token', '_method', 'categories', 'image'),
                    compact('image')
                );

        $product->update($data);

        $product->categories()->sync($categories);

        session()->flash('message', 'Product updated successfully.');

        return redirect()->route('admin.products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if ($product->image) {
            Storage::delete($product->image);
        }

        $product->delete();

        return response()->json(['success' => true]);
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.templates.default')

@section('title', 'Create a Product')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">

        <div class="card-header">
          <h3 class="card-title">Create Product</h3>
        </div>

        <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
          @csrf

          <div class="card-body">
            <div class="form-group">
              <label for="">Product Name</label>
              <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter a Product name" value="{{ old('name') }}">

               @error('name')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

             <div class="form-group">
              <label for="">Product description</label>
              <textarea name="description" id="description" rows="4" class="form-control @error('description') is-invalid @enderror" placeholder="Product description">{{ old('description') }}</textarea>

               @error('description')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product Image</label>
              <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" placeholder="Enter a Product image" value="{{ old('image') }}">

               @error('image')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product Categories</label>
              <select name="categories[]" id="" class="form-control select2bs4" multiple>
                @foreach ($categories as $category)
                  <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
              </select>

               @error('categories')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product Price</label>
              <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" placeholder="Enter Product price" value="{{ old('price') }}">

               @error('price')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product qty</label>
              <input type="text" name="qty" class="form-control @error('qty') is-invalid @enderror" placeholder="Enter Product qty" value="{{ old('qty') }}">

               @error('qty')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>


          </div>

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Add</button>
          </div>
        </form>

      </div>
    </div>
  </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>
    <script>
      $(function() {
        $('.select2').select2();

        $('.select2bs4').select2({
          theme: 'bootstrap4'
        });
      })
    </script>
@endpush

resources/views/admin/product/edit.blade.php
@extends('admin.templates.default')

@section('title', 'Edit Product')

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">

        <div class="card-header">
          <h3 class="card-title">Edit Product</h3>
        </div>

        <form action="{{ route('admin.products.update', $product) }}" method="POST" enctype="multipart/form-data">
          @csrf
          @method("PUT")

          <div class="card-body">
            <div class="form-group">
              <label for="">Product Name</label>
              <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter a Product name" value="{{ old('name') ?? $product->name }}">

               @error('name')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

             <div class="form-group">
              <label for="">Product description</label>
              <textarea name="description" id="description" rows="4" class="form-control @error('description') is-invalid @enderror" placeholder="Product description">{{ old('description') ?? $product->description }}</textarea>

               @error('description')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product Image</label>
              <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" placeholder="Enter a Product image" value="{{ old('image') }}">

               @error('image')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product Categories</label>
              <select name="categories[]" id="" class="form-control select2bs4" multiple>
                @foreach ($categories as $category)
                  <option value="{{ $category->id }}" @if ($product->categories->contains($category))
                      selected="selected"
                  @endif>{{ $category->name }}</option>
                @endforeach
              </select>

               @error('categories')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product Price</label>
              <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" placeholder="Enter Product price" value="{{ old('price') ?? $product->price }}">

               @error('price')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>

            <div class="form-group">
              <label for="">Product qty</label>
              <input type="text" name="qty" class="form-control @error('qty') is-invalid @enderror" placeholder="Enter Product qty" value="{{ old('qty') ?? $product->qty }}">

               @error('qty')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>


          </div>

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </form>

      </div>
    </div>
  </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>
    <script>
      $(function() {
        $('.select2').select2();

        $('.select2bs4').select2({
          theme: 'bootstrap4'
        });
      })
    </script>
@endpush

resources/views/admin/product/index.blade.php
@extends('admin.templates.default')

@section('title', 'Data Products')

@section('content')
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Data Products</h3>
    </div>
    <div class="card-body">
      @if(session()->has('message'))
        <div class="alert alert-info">{{ session('message')  }}</div>
      @endif
      <a href="{{ route('admin.products.create')  }}" class="btn btn-primary mb-4">Add Product</a>
      <table id="dataTable" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>No</th>
            <th>Name</th>
            <th>Description</th>
            <th>Image</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Action</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">
@endpush

@push('scripts')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script>
  $(function() {
    $('#dataTable').DataTable({
      "processing": true,
      "serverSide": true,
      "responsive": true,
      "autoWidth": true,
      ajax: '{{ route('admin.products.data') }}',
      columns: [
        {data: 'DT_RowIndex', orderable: false, searachable: false},
        {data: 'name'},
        {data: 'description'},
        {data: 'image'},
        {data: 'price'},
        {data: 'qty'},
        {data: 'action'},
      ]
    })
  })

  $('#dataTable').on('click', 'button#delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    console.log(id);
    Swal.fire({
      title: 'Kamu yakin hapus data ini?',
      text: "Data yang dihapus tidak bisa dikembalikan!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Oke, Hapus!',
      cancelButtonText: 'Batalkan',
    }).then((result) => {
      if (result.value) {
        $.ajax({
          type: 'DELETE',
          url: '/admin/products/'+ id,
          data: {
            'id': id,
             '_token': "{{ csrf_token() }}"
          },
          success: function(response) {
            Swal.fire(
              'Dihapus!',
              'Data berhasil dihapus.',
              'success'
            )

            location.reload(true);
          },
        });
      }
    })
  })

</script>
@endpush